### ISSUE TITLE
Different colorscheme than the one on vimcolorschemes

### ISSUE THREAD

**Issue by quietcaster** [4513ECHO/vim-colors-hatsunemiku#3]
Hi, 

I was wondering why there's a difference of colors in here and in vim colorschemes.
https://vimcolorschemes.com/4513echo/vim-colors-hatsunemiku

Thanks.

Sincerely,
quiet

**Comment by 4513ECHO** [comment]
Could you tell me detail for where there is a difference of colors?

**Comment by quietcaster** [comment]
For the lualine I mean. The colors are very muted compared to the vimcolorschemes.

**Comment by 4513ECHO** [comment]
Thanks for report.
Hmm, vim-colors-hatsunemiku does not  support for lualine.
I am not familiar with lualine. I, however,  have heard that lualine can generate theme from a current used color scheme.
Because [estilo](https://github.com/jacoborus/estilo), which is template engine used in this color scheme,  does not support lualine officially, I think it is hard to support lualine in vim-colors-hatsunemiku.
I have plan to change template engine and support lualine, but it will be a long way off.

**Comment by quietcaster** [comment]
Oops, I got it wrong. It was supposed to be lightline. My bad. Other than the lightline, the rest is great. I dig the colors for syntax highlight. Keep up the good work!
